addons:
  apt:
    update: true

# blocklist
branches:
  except:
  - legacy
  - experimental

# safelist
branches:
  only:
  - master
  - stable
  - develop

language: python

python:
  - 3.6.5

before_install:
  - sudo apt-get -y install postgresql
  - sudo apt-get -y install postgis
  - sudo apt-get -y install gdal-bin

install:
  - pip3 install -r requirements.txt

script:
  - python3 manage.py migrate
  - python3 manage.py test

