addons:
  apt:
    update: true

# blocklist
branches:
  except:
  - legacy
  - experimental

# safelist
branches:
  only:
  - master
  - stable
  - dev

language: python

python:
  - 3.6.5

install:
  - pip install pipenv

script:
  - python test.py
