addons:
  apt:
    update: true

# blocklist
branches:
  except:
  - legacy
  - experimental

# safelist
branches:
  only:
  - master
  - stable
  - develop

language: python

python:
  - 3.6.5

before_install:
  - sudo apt-get remove -y postgresql-9.1
  - sudo apt-get remove -y postgresql-9.2
  - sudo apt-get remove -y postgresql-9.3
  - sudo apt-get remove -y postgresql-9.4
  - sudo apt-get update -qq
  - sudo apt-get upgrade -qq -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
  - sudo apt-get -y install postgresql
  - sudo apt-get -y install postgis
  - sudo apt-get -y install gdal-bin

install:
  - pip3 install -r requirements.txt

script:
  - python3 manage.py migrate
  - python3 manage.py test

