addons:
  apt:
    update: true

# blocklist
branches:
  except:
  - legacy
  - experimental

# safelist
branches:
  only:
  - master
  - stable
  - develop

language: python

python:
  - 3.6.5

install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run python3 manage.py migrate

script:
  - pipenv run python3 manage.py test
