addons:
  apt:
    update: true

# blocklist
branches:
  except:
  - legacy
  - experimental

# safelist
branches:
  only:
  - master
  - stable
  - develop

language: python

python:
  - 3.6.5

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433

sudo: required

before_install:
  - sudo apt-get -y install gdal-bin

install:
  - pip3 install -r requirements.txt

before_script:
  - psql -c "create extension postgis" -U travis
  - psql -c "create database visiteydb;" -U travis
  - psql -c "CREATE USER server WITH PASSWORD 'pass';" -U travis
  - psql -c "alter USER server WITH SUPERUSER;" -U travis
  - psql -c "GRANT ALL ON DATABASE visiteydb  TO server;" -U travis

script:
  - python3 manage.py migrate
  - python3 manage.py test

