# blocklist
branches:
  except:
  - legacy
  - experimental

# safelist
branches:
  only:
  - master
  - stable
  - dev

install:
  - pip install -r requirements.txt

language: python

python:
  - 3.6.5

script:
  - coverage run test.py
