addons:
  apt:
    update: true

# blocklist
branches:
  except:
  - legacy
  - experimental

# safelist
branches:
  only:
  - master
  - stable
  - develop

language: python

python:
  - 3.6.5

services:
  - postgresql

addons:
  postgresql: "9.6"

sudo: required

before_install:
  - sudo apt-get -y install gdal-bin

install:
  - pip3 install -r requirements.txt

before_script:
  - sudo apt-get install postgresql-9.6-postgis-2.3 postgis -y -q
  - psql -c "create extension postgis" -U postgres
  - psql -c "create database visiteydb;" -U postgres
  - psql -c "CREATE USER server WITH PASSWORD 'pass';" -U postgres
  - psql -c "alter USER server WITH SUPERUSER;" -U postgres
  - psql -c "GRANT ALL ON DATABASE visiteydb  TO server;" -U postgres

script:
  - python3 manage.py migrate
  - python3 manage.py test

