addons:
  apt:
    update: true

# blocklist
branches:
  except:
  - legacy
  - experimental

# safelist
branches:
  only:
  - master
  - stable
  - develop

language: python

python:
  - 3.6.5

install:
  - pipenv install

script:
  - python3 manage.py migrate
  - python3 manage.py test

