# Generated by Django 2.0.6 on 2018-06-20 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rest_geo', '0002_auto_20180606_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointofinterest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={},
        ),
    ]
