# Generated by Django 2.0.6 on 2018-06-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_geo', '0003_auto_20180620_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointofinterest',
            options={'ordering': ('title',), 'verbose_name': 'PointOfInterest', 'verbose_name_plural': 'PointOfInterest'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ('title',), 'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
    ]
