# Generated by Django 2.0.5 on 2018-05-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_friendship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
