# Generated by Django 2.0.5 on 2018-05-20 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(blank=True, default='', max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('desc', models.TextField(blank=True, default='', max_length=100)),
                ('gender', models.CharField(blank=True, default='male', max_length=100)),
                ('birthdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='birthdate')),
                ('phone_number', models.CharField(blank=True, default='', max_length=100)),
                ('relationship', models.CharField(blank=True, default='', max_length=100)),
                ('rank', models.IntegerField(default=0)),
                ('blacklist', models.ManyToManyField(default=None, related_name='_profile_blacklist_+', to='rest_profile.Profile')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
