# Generated by Django 2.0.5 on 2018-05-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_profile', '0003_remove_profile_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blacklist',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='_profile_blacklist_+', to='rest_profile.Profile'),
        ),
    ]
