# Generated by Django 2.0.6 on 2018-06-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_profile', '0004_auto_20180605_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pseudo',
            field=models.CharField(blank=True, default='owner.username', max_length=15),
        ),
    ]
