# Generated by Django 2.0.6 on 2018-06-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_profile', '0005_auto_20180606_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pseudo',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
