# Generated by Django 2.0.6 on 2018-06-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_profile', '0006_auto_20180606_1024'),
        ('rest_profile', '0008_auto_20180620_1723'),
    ]

    operations = [
    ]
